networks:
  compareanything-net:
    driver: overlay

services:
  compareanything-backend:
    image: ghcr.io/jamez667/compareanything-backend:latest
    environment:
      - PORT=8080
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost}
    networks:
      - compareanything-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
        failure_action: rollback
        delay: 5s
      resources:
        limits:
          memory: 64M

  compareanything-frontend:
    image: ghcr.io/jamez667/compareanything-frontend:latest
    ports:
      - "3011:80"
    networks:
      - compareanything-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
        failure_action: rollback
        delay: 5s
      resources:
        limits:
          memory: 32M
